### PR TITLE
awscli: Create directory prefix first before uploading object

### LINKED ISSUE #231: Gateway: Awscli head-object test fails
Awscli headobject test fails on all gateways.
Here is the failure entry

```

{"name": "awscli", "duration": 7574, "function": "aws --endpoint-url http://192.168.86.102:9000 s3api head-object --bucket awscli-mint-test-bucket-11375 --key prefix/directory/\n", "status": "FAIL", "error": "An error occurred (404) when calling the HeadObject operation: Not Found"}

```
This call succeeds on regular server mode.

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #231

### CODE REVIEW

File: run/core/awscli/test.sh [hunk 1]
```diff
@@ -186,16 +186,26 @@ function test_lookup_object_prefix() {
     bucket_name=$(make_bucket)
     rv=$?
 
-    # if make bucket succeeds upload a file
     if [ $rv -eq 0 ]; then
-        function="${AWS} s3api put-object --body ${MINT_DATA_DIR}/datafile-1-MB --bucket ${bucket_name} --key prefix/directory/datafile-1-MB"
+        touch /tmp/zero-byte-file
+        function="${AWS} s3api put-object --body /tmp/zero-byte-file --bucket ${bucket_name} --key prefix/directory/"
```
Comment (nitisht) [inline run/core/awscli/test.sh]: put-object with no --body should works as well

File: run/core/awscli/test.sh [hunk 2]
```diff
@@ -186,16 +186,26 @@ function test_lookup_object_prefix() {
...
         out=$($function 2>&1)
         rv=$?
+        rm -f /tmp/zero-byte-file
     else
         # if make_bucket fails, $bucket_name has the error output
         out="${bucket_name}"
     fi
 
+    # if make bucket succeeds upload a file
```
Comment (nitisht) [inline run/core/awscli/test.sh]: comment can be updated

**Comment by harshavardhana** [comment]
Fixed and updated @nitisht @krisis
