### PR TITLE
[awscli] Should stop the execution incase of a test case failure

### LINKED ISSUE #296: awscli: Functional test fails and continues execution
```
{"name": "awscli", "duration": 1167, "function": "make_bucket\n", "status": "PASS"}
{"name": "awscli", "duration": 1623, "function": "aws --endpoint-url http://192.168.86.26:9000 s3api get-object --bucket awscli-mint-test-bucket-32170 --key datafile-1-MB /tmp/datafile-1-MB\n", "status": "PASS"}
{"name": "awscli", "duration": 4941, "function": "aws --endpoint-url http://192.168.86.26:9000 s3api head-object --bucket awscli-mint-test-bucket-4376 --key prefix/directory/\n", "status": "FAIL", "error": "An error occurred (404) when calling the HeadObject operation: Not Found"}
{"name": "awscli", "duration": 2301, "function": "aws --endpoint-url http://192.168.86.26:9000 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-14263/datafile-65-MB\n", "status": "PASS"}
{"name": "awscli", "duration": 2155, "function": "aws --endpoint-url http://192.168.86.26:9000 s3 sync /mint/data s3://awscli-mint-test-bucket-3945/\n", "status": "PASS"}
{"name": "awscli", "duration": 2234, "function": "aws --endpoint-url http://192.168.86.26:9000 s3api list-objects-v2 --bucket awscli-mint-test-bucket-3817 --prefix datafile-1-MB --max-keys=-1\n", "status": "PASS"}
{"name": "awscli", "duration": 4265, "function": "aws --endpoint-url http://192.168.86.26:9000 s3api put-object --body /mint/data/datafile-1-MB --bucket awscli-mint-test-bucket-19111 --key datafile-1-MB --content-length -1\n", "status": "PASS"}
```

Awscli doesn't stop execution even after a failure. The test here is wrong and needs to be fixed. This can be reproduced by running minio in FS mode and running awscli sdk 's mint test

### PR DESCRIPTION
**Pull request by Praveenrajmani**
This PR fixes
- Bars the execution of the remaining test cases incase of a test case failure inbetween.
- Removes the unwanted `head-object` test case, Because this wont apply for both s3/minio [Tested]
  
<b>s3</b>
image

<b>minio</b>
image

And the reason for removing the unwanted test case is because

We already do a `delete-object` [https://github.com/minio/mint/blob/c5035ea2fa7f979a98f6a961d8ecc1ce77611672/run/core/awscli/test.sh#L228](url), We should expect a `400`.

And we already have similar `head-object` test [https://github.com/minio/mint/blob/c5035ea2fa7f979a98f6a961d8ecc1ce77611672/run/core/awscli/test.sh#L246](url). 

Fixes #296

### CODE REVIEW

File: run/core/awscli/test.sh [hunk 1]
```diff
@@ -248,23 +248,16 @@ function test_lookup_object_prefix() {
...
+        if [ $rv -eq 0 ]; then
+            # clean up and log error
+            ${AWS} s3 rb s3://"${bucket_name}" --force > /dev/null 2>&1
+            log_failure "$(get_duration "$start_time")" "${function}" "${out}"
+            return 1
+        fi
+        rv=0
     fi
 
-    # Request should fail.
```
Comment (Praveenrajmani) [inline run/core/awscli/test.sh]: Simplified this because the error code check here is specific to the head-object case before it. This might produce inconsistent error logs if left unchanged.

File: run/core/awscli/test.sh [hunk 2]
```diff
@@ -1203,7 +1196,7 @@ main() {
     test_multipart_upload_10 && \
     test_serverside_encryption && \
     test_serverside_encryption_get_range && \
-    test_serverside_encryption_multipart
+    test_serverside_encryption_multipart &&
```
Comment (balamurugana) [inline run/core/awscli/test.sh]: Syntax error

Comment (Praveenrajmani) [reply run/core/awscli/test.sh]: oops.. Fixed

File: run/core/awscli/test.sh [hunk 3]
```diff
@@ -248,23 +248,16 @@ function test_lookup_object_prefix() {
         test_function=${function}
         out=$($function 2>&1)
         rv=$?
+        # Request should fail.
```
Comment (balamurugana) [inline run/core/awscli/test.sh]: Unable to understand why this change required i.e. no logic is changed except nested `if`

Comment (Praveenrajmani) [reply run/core/awscli/test.sh]: yes there is no  logical change here, just to simplify the code and the below reason justifies it.
This particular test here [https://github.com/minio/mint/blob/c5035ea2fa7f979a98f6a961d8ecc1ce77611672/run/core/awscli/test.sh#L254](url) is specific to [https://github.com/minio/mint/blob/c5035ea2fa7f979a98f6a961d8ecc1ce77611672/run/core/awscli/test.sh#L246](url) this head-object test for which the <b>request should fail</b>. So this should not be generic. (executes all the time even if the `head object` test is not executed)

Comment (balamurugana) [reply run/core/awscli/test.sh]: Nested `if` does not make simplification; rather it should be avoided.
