### PR TITLE
Log test results one json object per test

### LINKED ISSUE #112: Update aws-sdk-php to output new mint log format
`aws-sdk-php` logs need to be updated in the format below so that `mint` logs can be easily parsed.
```
{
    "name":"mc", // SDK Name
    "function":"testPresignGetObject", // Test function name
    "description": "test function description (optional)", //  Test function description
    "args":"", // key value map, varName:value. Only arguements that devs may be interested in
    "duration":"", // duration of the whole test
    "status":"", // can be PASS, FAIL, NA
    "alert":"failed to download pre-signed object(optional)", // error related, human readable message. Should be taken care of if present
    "error":"stack-trace/exception message(only in case of failure)" // actual low level exception/error thrown by the program
}
```

### PR DESCRIPTION
**Pull request by krisis**
Based on the following spec,
```

{
  "name":"mc",                                                     // SDK Name
  "function":"makeBucket(String bucketName)",                      // API name
  "args":"",                                                       // key value map, varName:value. Only arguements that devs may be interested in
  "duration":"15",                                                 // duration of the whole test in milli seconds
  "status":"PASS",                                                 // can be PASS, FAIL, NA
  "alert":"Information like whether this is a Blocker/ Gateway, Server etc can go here",
  "message":" descriptive error message"                           // error related, human readable  message. Should be taken care of if present
  "error":"stack-trace/exception message(only in case of failure)" // actual low level exception/error thrown by the program
}

```
Fixes  #112

### CODE REVIEW

**Comment by NitishT** [comment]
`ms` can be removed from the duration section, unit is implicit. 

Output: 

```
{
  "name": "aws-sdk-php",
  "function": "getBucketLocation ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413"
  },
  "duration": "5ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "listBuckets ( array $params = [] )",
  "args": [],
  "duration": "8ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "47ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "listMultipartUploads ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "159ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "headBucket ( array $params = [] )",
  "args": [
    "aws-sdk-php-bucket-20413",
    "aws-sdk-php-bucket-10432"
  ],
  "duration": "11ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-bucket-20413": "obj1",
    "aws-sdk-php-bucket-10432": "obj2"
  },
  "duration": "5ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "getObject ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "11ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "copyObject ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "13ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "deleteObjects (array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "23ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "anonDeleteObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "34ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "createMultipartUpload ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "259ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "uploadPart ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "154ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "abortMultipartupload ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-20413",
    "Object": "obj1"
  },
  "duration": "32ms",
  "status": "PASS"
}
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-bucket-42310"
  },
  "duration": "57ms",
  "status": "PASS"
}

```

File: run/core/aws-sdk-php/quick-tests.php [hunk 1]
```diff
@@ -925,23 +950,36 @@ function cleanupSetup($s3Client, $objects) {
...
-        $counter++;
+        $end_time = microtime();
+        $json_log = [
+            "name" => "aws-sdk-php",
+            "function" => $fnSignature,
+            "args" => $args, // FIXME: key-value map of input args
+            "duration" => sprintf("%dms", ($end_time - $start_time) * 1000), // elapsed time in ms
+            "status" => $status,
+        ];
+        if ($error !== "") {
```
Comment (NitishT) [inline run/core/aws-sdk-php/quick-tests.php]: should this be `($error != "")` ?

Comment (krisis) [reply run/core/aws-sdk-php/quick-tests.php]: I preferred `!==` over `!=` for the following reason.
> Example | Name | Result
> $a !== $b | Not identical | TRUE if $a is not equal to $b, or they are not of the same type.

Ref: https://secure.php.net/manual/en/language.operators.comparison.php

Comment (NitishT) [reply run/core/aws-sdk-php/quick-tests.php]: got it. :+1:

File: run/core/aws-sdk-php/quick-tests.php [hunk 2]
```diff
@@ -925,23 +950,36 @@ function cleanupSetup($s3Client, $objects) {
...
-        $counter++;
+        $end_time = microtime();
+        $json_log = [
+            "name" => "aws-sdk-php",
+            "function" => $fnSignature,
+            "args" => $args,
+            "duration" => sprintf("%d", ($end_time - $start_time) * 1000), // elapsed time in ms
+            "status" => $status,
+        ];
+        if ($error !== "") {
```
Comment (ebozduman) [inline run/core/aws-sdk-php/quick-tests.php]: I have a single comment and request for a change.
Although it may not be that intuitive, the decision made for the spec dictates...
`"error"` field is for low level error information like stack trace info etc., and the `"message"` filed is for error messages.

Spec:
```
  :
  :
  :
  "alert":"Information like whether this is a Blocker/ Gateway, Server etc can go here",
  "message":" descriptive error message"                           // error related, human readable  message. Should be taken care of if present
  "error":"stack-trace/exception message(only in case of failure)" // actual low level exception/error thrown by the program
```
Please replace `error` for `message`.

File: run/core/aws-sdk-php/quick-tests.php [hunk 3]
```diff
@@ -143,7 +143,8 @@ function runExceptionalTests($s3Client, $apiCall, $exceptionMatcher, $exceptionP
 function testListBuckets(S3Client $s3Client) {
     $buckets = $s3Client->listBuckets();
     foreach ($buckets['Buckets'] as $bucket){
-        echo $bucket['Name']."\n";
+        // Uncomment the following line during debugging.
```
Comment (ebozduman) [inline run/core/aws-sdk-php/quick-tests.php]: I think it would be better to define a debug mode, that can be turned on and off, in the code to eliminate manually commenting out all the debug print out/echo lines one by one when done testing and the opposite when debugging.

https://stackoverflow.com/questions/10397454/php-turn-on-off-able-function-to-print-debugging-messages

Here is one way to achieve it:
```
$debugmode = true;

interface Debugger {
    public function out($data);
}

class EchoDebugger implements Debugger {
    public function out($data) {
        echo $data;
    }
}

class NullDebugger implements Debugger {
    public function out($data) {
        // Do nothing
    }
}

if($debugmode)
    $debugger = new EchoDebugger();
else
    $debugger = new NullDebugger();

$debugger->out('This will be output if $debugmode is true');
```

File: run/core/aws-sdk-php/quick-tests.php [hunk 4]
```diff
@@ -994,20 +1020,21 @@ function runTestFunction($myfunc, ...$args) {
...
-    runTestFunction('testCopyObject', $s3Client, $firstBucket, $firstObject);
-    runTestFunction('testDeleteObjects', $s3Client, $firstBucket, $firstObject);
-    runTestFunction('testAnonDeleteObjects', $anonymousClient, $s3Client, $firstBucket, $firstObject);
-    runTestFunction('testMultipartUpload', $s3Client, $firstBucket, $firstObject);
-    runTestFunction('testMultipartUploadFailure', $s3Client, $firstBucket, $firstObject);
-    runTestFunction('testAbortMultipartUpload', $s3Client, $firstBucket, $firstObject);
-    runTestFunction('testBucketPolicy', $s3Client, $emptyBucket);
+    $testParams = ['Bucket' => $firstBucket, 'Object' => $firstObject];
+    runTestFunction($s3Client, 'testGetBucketLocation', "getBucketLocation ( array \$params = [] )", ['Bucket' => $firstBucket]);
+    runTestFunction($s3Client, 'testListBuckets', "listBuckets ( array \$params = [] )", []);
```
Comment (ebozduman) [inline run/core/aws-sdk-php/quick-tests.php]: PHP function definition supports default parameter values when there are no parameters to pass to the function, like
`function runTestFunction($s3Client, $myfunc, $fnSignature, $args) {`
=>
`function runTestFunction($s3Client, $myfunc, $fnSignature, $args = []) {`
