### PR TITLE
Fix log parsing to check for lowercase fail in status

### LINKED ISSUE #233: Error entry not displayed in case of failure
When minio-go fails, the last entry, which is the failure is not displayed.

Here is the display on the screen

```
Running with
SERVER_ENDPOINT: 192.168.1.102:9000
ACCESS_KEY:      ***REDACTED***
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       full

To get logs, run 'sudo docker cp 2e7c5914be92:/mint/log /tmp/mint-logs'
(1/1) Running minio-go tests ... FAILED in 30 seconds

Executed 0 out of 1 tests successfully.

```

### PR DESCRIPTION
**Pull request by nitisht**
Fixes #233 

While https://github.com/minio/minio-go/pull/865 updates the minio-go logs to print `FAIL` as status instead of `fail`, to avoid further issues, we should check for both values in Mint as well.

### CODE REVIEW

File: mint.sh [hunk 1]
```diff
@@ -78,7 +78,7 @@ function run_test()
         fi
         ## Show error.log when status is empty or not "FAIL".
         ## This may happen when test run failed without providing logs.
-        if [ "$jq_rv" -ne 0 ] || [ -z "$status" ] || [ "$status" != "FAIL" ]; then
+        if [ "$jq_rv" -ne 0 ] || [ -z "$status" ] || [ "$status" != "FAIL" ] && [ "$status" != "fail" ]; then
```
Comment (balamurugana) [inline mint.sh]: Why do we need to support lowercase `"fail"`?  We decided to status to be a enum value than any string.

Comment (nitisht) [reply mint.sh]: I understand each language SDK should log the status field as an enum with only three values `FAIL`, `PASS` or `NA`. Few SDKs are not yet doing that (example: https://github.com/minio/mint/blob/master/run/core/aws-sdk-go/quick-tests.go#L92). 

While we need to fix those SDKs, Mint should be defensive in checking these values so further such problems (status case not matching) do not report false positives.

**Comment by nitisht** [comment]
@kannappanr PR is updated, please check
