### PR TITLE
s3cmd: handle errors properly

### LINKED ISSUE #193: s3cmd fails on azure gateway
Below is an error while running mint
```
Running s3cmd tests ... FAILED in 3 seconds
parse error: Invalid numeric literal at line 1, column 101
```

### PR DESCRIPTION
**Pull request by balamurugana**
Fix #193 #201

### CODE REVIEW

File: run/core/s3cmd/test.sh [hunk 1]
```diff
@@ -121,12 +121,13 @@ function assert()
...
     shift
 
-    err=$("$@")
+    err=$("$@" 2>&1)
     rv=$?
     if [ "$rv" -ne 0 ] && [ "$expected_rv" -eq 0 ]; then
         if [ -n "$MINT_MODE" ]; then
-            err=$(python -c 'import sys,json; print(json.dumps(sys.stdin.read()))' <<<"$err")
-            printf '{"name": "s3cmd", "duration": "%d", "function": "%s", "status": "FAIL", "error": "%s"}\n' "$(get_duration "$start_time")" "$func_name" "$err"
+            err=$(printf "$err" | python -c 'import sys,json; print(json.dumps(sys.stdin.read()))')
```
Comment (nitisht) [inline run/core/s3cmd/test.sh]: Shellcheck issue:

In run/core/s3cmd/test.sh line 128:
 err=$(printf "$err" | python -c 'import sys,json; print(json.dumps(sys.stdin.read()))')
 ^-- SC2059: Don't use variables in the printf format string. Use printf "..%s.." "$foo".
